// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makePostRoute, makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as AmaRoute from "@/app/ama/page.info";
import * as AmaRoomIdRoute from "@/app/ama/[roomId]/page.info";
import * as ApiAuthNextauthRoute from "@/app/api/auth/[...nextauth]/route.info";
import * as ApiCreateRoomRoute from "@/app/api/createRoom/route.info";
import * as ApiJoinRoomRoute from "@/app/api/joinRoom/route.info";
import * as DashboardRoute from "@/app/dashboard/page.info";
import * as PrivacypolicyRoute from "@/app/privacy-policy/page.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const Ama = makeRoute(
  "/ama",
  {
    ...defaultInfo,
    ...AmaRoute.Route
  }
);
export const AmaRoomId = makeRoute(
  "/ama/[roomId]",
  {
    ...defaultInfo,
    ...AmaRoomIdRoute.Route
  }
);
export const ApiAuthNextauth = makeRoute(
  "/api/auth/[...nextauth]",
  {
    ...defaultInfo,
    ...ApiAuthNextauthRoute.Route
  }
);
export const Dashboard = makeRoute(
  "/dashboard",
  {
    ...defaultInfo,
    ...DashboardRoute.Route
  }
);
export const Privacypolicy = makeRoute(
  "/privacy-policy",
  {
    ...defaultInfo,
    ...PrivacypolicyRoute.Route
  }
);

export const postApiCreateRoom = makePostRoute(
  "/api/createRoom",
  {
    ...defaultInfo,
    ...ApiCreateRoomRoute.Route
  },
  ApiCreateRoomRoute.POST
);
export const postApiJoinRoom = makePostRoute(
  "/api/joinRoom",
  {
    ...defaultInfo,
    ...ApiJoinRoomRoute.Route
  },
  ApiJoinRoomRoute.POST
);
